import type { HorseColor } from './horse.types';

export const HORSE_COUNT = 20;
export const CONDITION_MIN = 1;
export const CONDITION_MAX = 100;

export const HORSE_NAMES: readonly string[] = [
    'Ada Lovelace',
    'Alan Turing',
    'Grace Hopper',
    'Katherine Johnson',
    'Dorothy Vaughan',
    'Mary Jackson',
    'Hedy Lamarr',
    'Joan Clarke',
    'Frances Allen',
    'Jean Bartik',
    'Betty Holberton',
    'Kay McNulty',
    'Ruth Teitelbaum',
    'Marlyn Meltzer',
    'Frances Spence',
    'Kathleen Booth',
    'Annie Easley',
    'Anita Borg',
    'Evelyn Berezin',
    'Lynn Conway',
    'Ida Rhodes',
    'Adele Goldstine',
    'Charles Babbage',
    'George Boole',
    'Herman Hollerith',
    'Konrad Zuse',
    'John von Neumann',
    'Claude Shannon',
    'John Backus',
    'John McCarthy',
    'Edsger Dijkstra',
    'Niklaus Wirth',
    'Dennis Ritchie',
    'Seymour Cray',
    'Gary Kildall',
    'Edgar Codd',
    'Peter Naur',
    'Kristen Nygaard',
    'Marvin Minsky',
    'Douglas Engelbart',
];

export const SILK_COLORS: readonly HorseColor[] = [
    { name: 'Scarlet', hex: '#c81d34' },
    { name: 'Maroon', hex: '#7a1f3d' },
    { name: 'Orange', hex: '#f17c1e' },
    { name: 'Gold', hex: '#f2b705' },
    { name: 'Lemon', hex: '#f7ee55' },
    { name: 'Lime', hex: '#9bd12f' },
    { name: 'Emerald', hex: '#18a164' },
    { name: 'Teal', hex: '#0b7070' },
    { name: 'Sky Blue', hex: '#6ec6f0' },
    { name: 'Royal Blue', hex: '#1f4fd1' },
    { name: 'Navy', hex: '#1b2a4a' },
    { name: 'Purple', hex: '#6a2fb5' },
    { name: 'Lavender', hex: '#b69cf2' },
    { name: 'Magenta', hex: '#c2168f' },
    { name: 'Pink', hex: '#f59ac0' },
    { name: 'Brown', hex: '#7b4a2a' },
    { name: 'Tan', hex: '#c89f73' },
    { name: 'Black', hex: '#151515' },
    { name: 'White', hex: '#f5f5f5' },
    { name: 'Gray', hex: '#8c939d' },
];
